//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFastfood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_CONTENT
    {
        public int quantity { get; set; }
        public decimal price { get; set; }
        public int id_order { get; set; }
        public int id_product { get; set; }
    
        public virtual TORDER TORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
